% scratch 27 a scirpt to revise segmenations generated by auto-seg
% function(scracth 26)

dirpath = "C:\Users\Zhehao\Dropbox (OIST)\My_Matlab\TEA\Function\SegData";


files = Extract.filename(dirpath,'*.mat')


for w = 1: length(files)
    reviseSeg(files{w});
    frame_h = get(handle(gcf),'JavaFrame');
    set(frame_h,'Maximized',1);
    waitfor(gcf)
end